### ISSUE TITLE
Migration from which-key v2 to v3 

### ISSUE THREAD

**Issue by wroyca** [loichyan/DeltaVim#10]
Hello o/

Lately, which-key saw a new revision which comes with a different way to handle (some) things, in particular, icons.

Bumping DeltaVim plugins will cause v3 to be automatically used, which in turn will cause icons to be visually duplicated, that is

`icon .. icon .. desc`

I'd make a PR to handle this, but I saw that you have your own way to manage mappings and icons in general and figured you'd probably want to handle this according to your preference. \:)

**Comment by loichyan** [comment]
> I'd make a PR to handle this

I've synced some updates from AstroNvim/AstroNvim, and this should be fixed in loichyan/DeltaVim@0ea38a556426.

> I saw that you have your own way to manage mappings and icons

Yes, this might look a bit complicated without documentation, so I added some in loichyan/DeltaVim@5e70c3cc125a :)

**Comment by wroyca** [comment]
> > I'd make a PR to handle this
> 
> I've synced some updates from AstroNvim/AstroNvim, and this should be fixed in [0ea38a556426](https://github.com/loichyan/DeltaVim/commit/0ea38a556426).
> 
> > I saw that you have your own way to manage mappings and icons
> 
> Yes, this might look a bit complicated without documentation, so I added some in [5e70c3cc125a](https://github.com/loichyan/DeltaVim/commit/5e70c3cc125a) :)

Brilliant, thank! :partying_face:
